import 'package:acroworld/presentation/components/appbar/custom_appbar_simple.dart';
import 'package:acroworld/presentation/screens/base_page.dart';
import 'package:acroworld/utils/constants.dart';
import 'package:flutter/material.dart';

class PrivacyPage extends StatelessWidget {
  const PrivacyPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return BasePage(
      appBar: const CustomAppbarSimple(title: 'Privacy Policy'),
      child: Padding(
        padding: const EdgeInsets.symmetric(
          horizontal: AppPaddings.medium,
          vertical: AppPaddings.large,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Text(
              'PRIVACY POLICY',
              style: textTheme.displayLarge?.copyWith(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                letterSpacing: 1.2,
              ),
            ),
            const SizedBox(height: 12),
            Text(
              'Last updated: 04.06.2024',
              style: textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurface.withOpacity(0.7),
                fontSize: 14,
              ),
            ),
            const SizedBox(height: 32),

            // Introduction
            _buildSection(
              context,
              null,
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\n'
              'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.',
            ),
            const SizedBox(height: 40),

            // Interpretation and Definitions
            _buildMainSection(
              context,
              'INTERPRETATION AND DEFINITIONS',
              [
                _SubSectionData(
                  'INTERPRETATION',
                  'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
                ),
                _SubSectionData(
                  'DEFINITIONS',
                  'For the purposes of this Privacy Policy:\n\n'
                      'Account means a unique account created for You to access our Service or parts of our Service.\n\n'
                      'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AcroWorld.\n\n'
                      'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.\n\n'
                      'Country refers to: Berlin, Germany\n\n'
                      'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n\n'
                      'Personal Data is any information that relates to an identified or identifiable individual.\n\n'
                      'Service refers to the Website.\n\n'
                      'Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n\n'
                      'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n\n'
                      'Website refers to AcroWorld, accessible from acroworld.de\n\n'
                      'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
                ),
              ],
            ),
            const SizedBox(height: 40),

            // Platform description
            _buildSection(
              context,
              null,
              'Our platform allows acrobatic instructors to offer tickets for their events and workshops. We do not tolerate any illegal, harmful, fraudulent or otherwise inappropriate activities on our platform. Any violation of this Acceptable Use Policy may result in exclusion from our platform.',
            ),
            const SizedBox(height: 40),

            // Acceptable Use Policy
            _buildMainSection(
              context,
              'ACCEPTABLE USE POLICY',
              [
                _SubSectionData(
                  'Acceptable Use:',
                  '• Offering tickets for acrobatic events, courses and workshops\n'
                      '• Booking of these offered events by users',
                ),
                _SubSectionData(
                  'Unacceptable Use:',
                  '• Offering or selling illegal products or services\n'
                      '• Uploading or distributing illegal, harmful, fraudulent, defamatory or copyrighted content\n'
                      '• Activities that violate applicable laws\n'
                      '• Any kind of fraud, manipulation or deception',
                ),
              ],
            ),
            const SizedBox(height: 40),

            // Controls for Acceptable Use Policy
            _buildSection(
              context,
              'CONTROLS FOR ACCEPTABLE USE POLICY',
              'We implement the following measures to ensure providers comply with our Acceptable Use Policy:\n\n'
                  '• Manual review of new provider accounts and their offerings before activation\n'
                  '• Regular monitoring of offerings by our moderation team\n'
                  '• Easy reporting option for users to flag suspicious offerings\n'
                  '• Immediate review of reported offerings and taking appropriate action up to account suspension for violations\n'
                  '• Close cooperation with authorities for any illegal activities',
            ),
            const SizedBox(height: 40),

            // Collecting and Using Your Personal Data
            _buildMainSection(
              context,
              'COLLECTING AND USING YOUR PERSONAL DATA',
              [
                _SubSectionData(
                  'PAYMENT DATA',
                  'To provide you with the payment functionalities for our services, we integrate with Stripe, a third-party payment processing service. When you make a purchase through our Service, you may need to provide certain financial information directly to our payment processor, including but not limited to your credit card number, the expiration date of your credit card, and your billing address. The processing of this information is governed by Stripe\'s Privacy Policy and security measures. We do not store or have access to your financial information. Stripe\'s use of your personal data is outlined on their website under their Privacy Policy.',
                ),
                _SubSectionData(
                  'LOCATION DATA FOR EVENTS',
                  'If you enable location services on your device, we collect and use your location data to offer you personalized event suggestions, such as AcroYoga events happening near you. This data helps us enhance your experience with our Service by providing you with content that is relevant to your whereabouts. You have the option to enable or disable location services through your device settings at any time.',
                ),
                _SubSectionData(
                  'PERSONAL DATA',
                  'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n'
                      '• Email address\n'
                      '• First name and last name\n'
                      '• Usage Data',
                ),
                _SubSectionData(
                  'USAGE DATA',
                  'Usage Data is collected automatically when using the Service.\n\n'
                      'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n'
                      'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\n'
                      'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
                ),
              ],
            ),
            const SizedBox(height: 40),

            // Tracking Technologies and Cookies
            _buildMainSection(
              context,
              'TRACKING TECHNOLOGIES AND COOKIES',
              [
                _SubSectionData(
                  null,
                  'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:\n\n'
                  'Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.\n\n'
                  'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies: Cookies by PrivacyPolicies Generator.',
                ),
                _SubSectionData(
                  null,
                  'We use both Session and Persistent Cookies for the purposes set out below:\n\n'
                  'Necessary / Essential Cookies\n'
                  'Type: Session Cookies\n'
                  'Administered by: Us\n'
                  'Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.\n\n'
                  'Cookies Policy / Notice Acceptance Cookies\n'
                  'Type: Persistent Cookies\n'
                  'Administered by: Us\n'
                  'Purpose: These Cookies identify if users have accepted the use of cookies on the Website.\n\n'
                  'Functionality Cookies\n'
                  'Type: Persistent Cookies\n'
                  'Administered by: Us\n'
                  'Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.\n\n'
                  'For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.',
                ),
              ],
            ),
            const SizedBox(height: 40),

            // Use of Your Personal Data
            _buildSection(
              context,
              'USE OF YOUR PERSONAL DATA',
              'The Company may use Personal Data for the following purposes:\n\n'
                  '• To provide and maintain our Service, including to monitor the usage of our Service.\n\n'
                  '• To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.\n\n'
                  '• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.\n\n'
                  '• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.\n\n'
                  '• To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.\n\n'
                  '• To manage Your requests: To attend and manage Your requests to Us.\n\n'
                  '• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.\n\n'
                  '• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.\n\n'
                  'We may share Your personal information in the following situations:\n\n'
                  '• With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.\n\n'
                  '• For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.\n\n'
                  '• With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.\n\n'
                  '• With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.\n\n'
                  '• With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.\n\n'
                  '• With Your consent: We may disclose Your personal information for any other purpose with Your consent.',
            ),
            const SizedBox(height: 40),

            // Retention of Your Personal Data
            _buildSection(
              context,
              'RETENTION OF YOUR PERSONAL DATA',
              'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\n'
                  'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
            ),
            const SizedBox(height: 40),

            // Transfer of Your Personal Data
            _buildSection(
              context,
              'TRANSFER OF YOUR PERSONAL DATA',
              'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.\n\n'
                  'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n\n'
                  'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
            ),
            const SizedBox(height: 40),

            // Disclosure of Your Personal Data
            _buildMainSection(
              context,
              'DISCLOSURE OF YOUR PERSONAL DATA',
              [
                _SubSectionData(
                  'BUSINESS TRANSACTIONS',
                  'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
                ),
                _SubSectionData(
                  'LAW ENFORCEMENT',
                  'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).',
                ),
                _SubSectionData(
                  'OTHER LEGAL REQUIREMENTS',
                  'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:\n\n'
                      '• Comply with a legal obligation\n'
                      '• Protect and defend the rights or property of the Company\n'
                      '• Prevent or investigate possible wrongdoing in connection with the Service\n'
                      '• Protect the personal safety of Users of the Service or the public\n'
                      '• Protect against legal liability',
                ),
              ],
            ),
            const SizedBox(height: 40),

            // Security of Your Personal Data
            _buildSection(
              context,
              'SECURITY OF YOUR PERSONAL DATA',
              'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
            ),
            const SizedBox(height: 40),

            // Background Location Data Collection
            _buildSection(
              context,
              'Background Location Data Collection',
              'If approved by the user, our app collects location data, even when the app is closed or not in use. This enables us to:\n\n'
                  'Local Event Discovery: By accessing your location, we can provide you with a curated list of AcroYoga events happening near you.\n\n'
                  'This data is not used for advertising purposes or to support ads in our application.',
            ),
            const SizedBox(height: 40),

            // Children's Privacy
            _buildSection(
              context,
              'CHILDREN\'S PRIVACY',
              'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.\n\n'
                  'If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent\'s consent before We collect and use that information.',
            ),
            const SizedBox(height: 40),

            // Links to Other Websites
            _buildSection(
              context,
              'LINKS TO OTHER WEBSITES',
              'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.\n\n'
                  'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
            ),
            const SizedBox(height: 40),

            // Changes to This Privacy Policy
            _buildSection(
              context,
              'CHANGES TO THIS PRIVACY POLICY',
              'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\n'
                  'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
            ),
            const SizedBox(height: 40),

            // Contact Us
            _buildSection(
              context,
              'CONTACT US',
              'If you have any questions about this Privacy Policy, You can contact us:\n\n'
                  'By email: info@acroworld.de',
            ),
            const SizedBox(height: 48),
          ],
        ),
      ),
    );
  }

  Widget _buildMainSection(
    BuildContext context,
    String title,
    List<_SubSectionData> subsections,
  ) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: textTheme.displayLarge?.copyWith(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            letterSpacing: 0.5,
          ),
        ),
        const SizedBox(height: 24),
        ...subsections.map((sub) => Padding(
              padding: const EdgeInsets.only(bottom: 24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  if (sub.title != null) ...[
                    Text(
                      sub.title!,
                      style: textTheme.titleMedium?.copyWith(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        letterSpacing: 0.3,
                      ),
                    ),
                    const SizedBox(height: 12),
                  ],
                  Text(
                    sub.content,
                    style: textTheme.bodyMedium?.copyWith(
                      fontSize: 15,
                      height: 1.6,
                      letterSpacing: 0.2,
                    ),
                  ),
                ],
              ),
            )),
      ],
    );
  }

  Widget _buildSection(
    BuildContext context,
    String? title,
    String content,
  ) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (title != null) ...[
          Text(
            title,
            style: textTheme.displayLarge?.copyWith(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              letterSpacing: 0.5,
            ),
          ),
          const SizedBox(height: 16),
        ],
        Text(
          content,
          style: textTheme.bodyMedium?.copyWith(
            fontSize: 15,
            height: 1.6,
            letterSpacing: 0.2,
          ),
        ),
      ],
    );
  }
}

class _SubSectionData {
  final String? title;
  final String content;

  _SubSectionData(this.title, this.content);
}
