// Map of country code to full country name.
const Map<String, String> stripeSupportedCountries = {
  "AU": "Australia",
  "AT": "Austria",
  "BE": "Belgium",
  "BG": "Bulgaria",
  "BR": "Brazil",
  "CA": "Canada",
  "HR": "Croatia",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "EE": "Estonia",
  "FI": "Finland",
  "FR": "France",
  "DE": "Germany",
  "GR": "Greece",
  "HK": "Hong Kong",
  "HU": "Hungary",
  // "IN": "India",       // India is not yet supported by Stripe (preview)
  // "ID": "Indonesia",   // Indonesia is not yet supported by Stripe (preview)
  "IE": "Ireland",
  "IT": "Italy",
  "JP": "Japan",
  "LV": "Latvia",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MY": "Malaysia",
  "MT": "Malta",
  "MX": "Mexico",
  "NL": "Netherlands",
  "NZ": "New Zealand",
  "NG": "Nigeria",
  "NO": "Norway",
  "PL": "Poland",
  "PT": "Portugal",
  "RO": "Romania",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "ZA": "South Africa",
  "ES": "Spain",
  "SE": "Sweden",
  "CH": "Switzerland",
  "TH": "Thailand",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
};

final Map<String, String> stripeSupportedCountryDialCodes = {
  "AU": "+61",
  "AT": "+43",
  "BE": "+32",
  "BG": "+359",
  "BR": "+55",
  "CA": "+1",
  "HR": "+385",
  "CY": "+357",
  "CZ": "+420",
  "DK": "+45",
  "EE": "+372",
  "FI": "+358",
  "FR": "+33",
  "DE": "+49",
  "GR": "+30",
  "HK": "+852",
  "HU": "+36",
  "IE": "+353",
  "IT": "+39",
  "JP": "+81",
  "LV": "+371",
  "LI": "+423",
  "LT": "+370",
  "LU": "+352",
  "MY": "+60",
  "MT": "+356",
  "MX": "+52",
  "NL": "+31",
  "NZ": "+64",
  "NG": "+234",
  "NO": "+47",
  "PL": "+48",
  "PT": "+351",
  "RO": "+40",
  "SG": "+65",
  "SK": "+421",
  "SI": "+386",
  "ZA": "+27",
  "ES": "+34",
  "SE": "+46",
  "CH": "+41",
  "TH": "+66",
  "AE": "+971",
  "GB": "+44",
  "US": "+1",
};

// Function to get the full country name from the country code.

String? getCountryName(String? countryCode) {
  if (countryCode == null || countryCode.isEmpty) {
    return null;
  }
  return allCountries[countryCode.toUpperCase()];
}

// Function to get the country code from the full country name.
String? getCountryCode(String? countryName) {
  if (countryName == null || countryName.isEmpty) {
    return null;
  }
  return allCountries.entries
      .firstWhere(
          (entry) => entry.value.toLowerCase() == countryName.toLowerCase(),
          orElse: () => MapEntry("", ""))
      .key;
}

// GENERATED — do not hand-edit.
// Sovereign states only.
const Map<String, String> allCountries = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AG': 'Antigua and Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BT': 'Bhutan',
  'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BR': 'Brazil',
  'BN': 'Brunei Darussalam',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'CV': 'Cabo Verde',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'KY': 'Cayman Islands',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CR': 'Costa Rica',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'CI': 'Côte d\'Ivoire',
  'CD': 'Democratic Republic of the Congo',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'SZ': 'Eswatini',
  'ET': 'Ethiopia',
  'FO': 'Faroe Islands',
  'FM': 'Federated States of Micronesia',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GA': 'Gabon',
  'GM': 'Gambia',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GR': 'Greece',
  'GL': 'Greenland',
  'GD': 'Grenada',
  'GP': 'Guadeloupe',
  'GT': 'Guatemala',
  'GG': 'Guernsey',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HN': 'Honduras',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IM': 'Isle of Man',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'XK': 'Kosovo',
  'KW': 'Kuwait',
  'KG': 'Kyrgyzstan',
  'LA': 'Laos',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MO': 'Macau',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MH': 'Marshall Islands',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'YT': 'Mayotte',
  'MX': 'Mexico',
  'MD': 'Moldova',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MS': 'Montserrat',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar',
  'NA': 'Namibia',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'KP': 'North Korea',
  'MK': 'North Macedonia',
  'MP': 'Northern Mariana Islands',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PW': 'Palau',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'QA': 'Qatar',
  'CG': 'Republic of the Congo',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SH': 'Saint Helena',
  'KN': 'Saint Kitts and Nevis',
  'LC': 'Saint Lucia',
  'PM': 'Saint Pierre and Miquelon',
  'VC': 'Saint Vincent and the Grenadines',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'Sao Tome and Principe',
  'SA': 'Saudi Arabia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'KR': 'South Korea',
  'SS': 'South Sudan',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'PS': 'State of Palestine',
  'SD': 'Sudan',
  'SR': 'Suriname',
  'SJ': 'Svalbard and Jan Mayen',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syria',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TK': 'Tokelau',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TM': 'Turkmenistan',
  'TV': 'Tuvalu',
  'TR': 'Türkiye',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States of America',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'WF': 'Wallis and Futuna',
  'EH': 'Western Sahara',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
};
