name: acroworld
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

######### VERSION ##########
version: 1.2.7+102
############################

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.0
  jwt_decode: ^0.3.1
  graphql_flutter: ^5.1.0
  event_bus: ^2.0.0
  firebase_messaging: ^14.6.8
  firebase_core: ^2.25.4
  readmore: ^2.2.0
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  pie_chart: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  package_info_plus: ^4.2.0
  flutter_html: ^3.0.0-beta.2
  photo_view: ^0.14.0
  location: ^5.0.3
  flutter_email_sender: ^6.0.2
  flutter_stripe: ^10.0.0
  sentry_flutter: ^7.13.2
  flutter_native_splash: ^2.3.8
  timeago: ^3.2.2
  table_calendar: ^3.0.5
  path_provider: ^2.0.10
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  image_path: "assets/logo/play_store_512.png"
  ios: true
  android: true
  remove_alpha_ios: true

# Activate script support with "dart pub global activate rps"
# Run scripts with "rps <script> <script-arguments>" e.g. "rps version patch"
scripts:
  version: sh ./scripts/version.sh

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
flutter_native_splash:
  color: "#ffffff"
  image: "assets/muscleup_drawing.png"
  android: true
  ios: true
