name: acroworld
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

######### VERSION ##########
version: 1.0.26+01
############################

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.9.2
  file_picker: ^4.3.2
  maps_launcher: ^2.0.1
  google_maps_flutter_web: ^0.3.2+1
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  http: ^0.13.4
  jwt_decode: ^0.3.1
  graphql_flutter: ^5.1.0
  google_maps_flutter: 2.1.8
  event_bus: ^2.0.0
  firebase_messaging: ^12.0.1
  firebase_core: ^1.20.0
  readmore: ^2.2.0
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  toggle_switch: ^2.0.1
  share_plus: ^4.5.3
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  timeago: ^3.2.2
  table_calendar: ^3.0.5
  path_provider: ^2.0.10


flutter_icons:
  image_path: "assets/logo/play_store_512.png"
  ios: true
  android: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
