name: acroworld
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

######### VERSION ##########
version: 2.2.2+143
############################

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.14.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.0
  jwt_decode: ^0.3.1
  graphql_flutter: ^5.1.0
  event_bus: ^2.0.0
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  pie_chart: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  package_info_plus: ^8.0.2
  flutter_html: ^3.0.0-beta.2
  photo_view: ^0.15.0
  location: ^6.0.2
  flutter_email_sender: ^6.0.2
  flutter_stripe: ^11.1.0
  sentry_flutter: ^8.9.0
  flutter_native_splash: ^2.3.8
  timeago: ^3.2.2
  table_calendar: ^3.0.5
  path_provider: ^2.0.10
  flutter_svg: ^2.0.10+1
  app_links: ^6.1.1
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  easy_stepper: ^0.8.5+1
  numberpicker: ^2.1.2
  firebase_storage: ^12.3.2
  timezone: ^0.9.4
  fl_chart: ^0.69.0
  uuid: ^4.5.1
  quill_html_editor: ^2.2.8
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: 'assets/logo/play_store_512.png'
  ios: true
  android: true
  remove_alpha_ios: true

# Activate script support with "dart pub global activate rps"
# Run scripts with "rps <script> <script-arguments>" e.g. "rps version patch"
# create script for flutter run -> flutter run --flavor dev --dart-define=app.flavor=dev
# create script for flutter run -> flutter run --flavor prod --dart-define=app.flavor=prod
# build api with prod flavor -> flutter build apk --flavor prod --dart-define=app.flavor=prod

scripts:
  version: sh ./scripts/version.sh
  run-dev: flutter run --flavor dev --dart-define=app.flavor=dev
  run-prod: flutter run --flavor prod --dart-define=app.flavor=prod

  run:web:dev: flutter run -d chrome --dart-define=app.flavor=dev
  run:web:prod: flutter run -d chrome --dart-define=app.flavor=prod

  build-prod: flutter build api --flavor prod --dart-define=app.flavor=prod

  run-android-prod: flutter run --dart-define=app.flavor=prod --release

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/muscleup_drawing.png'
  android: true
  ios: true
