// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:acroworld/environment.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = AppEnvironment.isProdBuild
      ? FirebaseOptions(
          apiKey: 'AIzaSyBBqCy5y5Zli55kvG4nQ4dRHo58JLmsFFA',
          appId: '1:322527689838:web:4fd883247e012ff8d8ba7f',
          messagingSenderId: '322527689838',
          projectId: 'arcoworld-1415b',
          authDomain: 'arcoworld-1415b.firebaseapp.com',
          storageBucket: 'arcoworld-1415b.appspot.com',
        )
      : FirebaseOptions(
          apiKey: 'AIzaSyD_Fn4O8ZqK4OQeIaCqlpo1vAQ2fEKM4UM',
          appId: '1:1077598628073:web:aa35f4763ac8f2a569a878',
          messagingSenderId: '1077598628073',
          projectId: 'acro-world-development',
          authDomain: 'acro-world-development.firebaseapp.com',
          storageBucket: 'acro-world-development.appspot.com',
          measurementId: 'G-CC01W3QM47',
        );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjE7Ifhq54h3WZ96OowouAezoTaOhpvrU',
    appId: '1:322527689838:android:6a03192dc02d2619d8ba7f',
    messagingSenderId: '322527689838',
    projectId: 'arcoworld-1415b',
    storageBucket: 'arcoworld-1415b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrEgJIfdilKn8rymGbZ11xM2hb0lCi7ms',
    appId: '1:322527689838:ios:74ac6ec191f0c5d4d8ba7f',
    messagingSenderId: '322527689838',
    projectId: 'arcoworld-1415b',
    storageBucket: 'arcoworld-1415b.appspot.com',
    iosBundleId: 'com.acroworld.community.ios.app',
  );
}
